---
- hosts: localhost

  tasks:
  - command: docker-machine config techtalklunch
    register: docker_host

  - name: Build the new application docker image
    command: docker {{docker_host}} build -t jcsirot/devoxxcarpet ..

  - name: Find the application container id
    command: docker {{docker_host}} ps -q
    register: container_id
    ignore_errors: True

  - name: Ensure the application is stopped
    command: docker {{docker_host}} stop {{container_id}}
    when: container_id is defined

  - name: Deploy the new application
    command: docker {{docker_host}} run -ti -e DATASTORE=false -d -p 80:8080 jcsirot/devoxxcarpet
