---
- hosts: localhost

  vars:
    docker_host: "$(docker-machine config techtalklunch)"

  tasks:
  - name: Build the new application docker image
    cmd: docker {{docker_host}} build -t jcsirot/devoxxcarpet ..

  - name: Find the application container id
    cmd: docker {{docker_host}} ps -q
    register: container_id
    ignore_errors: True

  - name: Ensure the application is stopped
    cmd: docker {{docker_host}} stop {{container_id}}
    when: container_id is defined

  - name: Deploy the new application
    cmd: docker {{docker_host}} run -ti -e DATASTORE=false -d -p 80:8080 jcsirot/devoxxcarpet
